name: Build wheels
on:
  push:
    branches:
      - master
      - update-cicd
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.0
        env:
          CIBW_TEST_SOURCES: tests
          CIBW_TEST_COMMAND: "pytest tests"
          CIBW_TEST_REQUIRES: pytest pytest-cov pytest-mock codecov
          CIBW_SKIP: cp38-* cp313-* pp* *-musllinux* *-manylinux_i686
 
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ github.run_id }}
          path: ./wheelhouse/*.whl
