name: Build wheels
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3
        env:
          CIBW_BEFORE_BUILD: pip install "cython>=0.29"
          CIBW_SKIP: cp36-* cp37-* cp313-* pp* *-musllinux* *-manylinux_i686

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ github.run_id }}
          path: ./wheelhouse/*.whl
